<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ErrorPage.aspx.cs" Inherits="ErrorPage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>GMS</title>
    <link type="text/css" rel="stylesheet" href="../bootstrap-dist/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="../bootstrap-dist/css/bootstrap-theme.min.css" />
    <link type="text/css" rel="stylesheet" href="../css/angular-ui-notification.min.css" />

    <link rel="stylesheet" href="../css/style.css" />
    <link href="../jss/jquery-ui.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="../js/angular.min.js"></script>
    <script src="../js/angular-route.min.js"></script>
    <script src="../js/underscore-min.js"></script>
    <script src="../js/ui-bootstrap-tpls-0.14.3.min.js"></script>
    <script src="../js/ng-map.min.js"></script>
    <script src="../js/jquery.min.js"></script>
    <script src="../jss/jquery-ui.min.js" type="text/javascript"></script>
    <script src="../js/jquery.plugin.min.js"></script>
    <script src="../js/jquery.datetimeentry.min.js"></script>
    <script src="../js/angular-ui-notification.min.js"></script>
    <script type="text/jscript" src="../bootstrap-dist/js/bootstrap.min.js"></script>
    <link href="../css/bootstrap-colorpicker.min.css" rel="stylesheet" />
    <script src="../js/bootstrap-colorpicker.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.2.0.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <!--Reference the StockTicker script. -->
    <script src="../StockTicker.js"></script>
    <script src="../jss/jquery-ui.min.js" type="text/javascript"></script>
    </head>
<body>
    <form id="form1" runat="server">
            <div class="container-fluid" data-ng-init="formType='help'">
            <div class="col-md-12">
                <div class="col-md-12">
                    <div class="row">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                                        <span class="sr-only"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <a href="Login.aspx" class="navbar-brand">GMS</a>
                                </div>
                            </div>
                            <!-- /.container-fluid -->
                        </nav>
                    </div>
                </div>
            </div>
                <div class="row">
        <div class="col-lg-12">
            <div class="col-md-12">
                <div class="row">
                <div class="col-lg-12">
                    <div style="text-align:center; font-size:large">
                        There was a problem with completing the previous request. Please hit the back button and try again.
                        Or contact your admin/engineer.
                    </div>
                </div>
                        
            </div>
        </div>
    </div>
        </div>
    </form>
</body></html>
